/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: neutralize (https://sketchfab.com/neutralize)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/baseball-bat-335a02885aee470d94dc3f031136dd84
title: Baseball bat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {animated} from "@react-spring/three"

export default function Baseball({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/baseball_bat/scene.gltf')
  return (
    <animated.group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.005']} />
      </group>
    </animated.group>
  )
}

useGLTF.preload('/models/baseball_bat/scene.gltf')
