/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KaitlinKelly (https://sketchfab.com/KaitlinK2000)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/file-cabinet-3716f3bbb40e4933b470398e7a8284a3
title: File Cabinet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {animated} from "@react-spring/three" 

export default function File({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/file_cabinet/scene.gltf')
  return (
    <animated.group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.lambert1} />
        </group>
      </group>
    </animated.group>
  )
}

useGLTF.preload('/models/file_cabinet/scene.gltf')
