/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Des'Lee (https://sketchfab.com/dexilee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/icon-folder-a3ada26dc877486db8acf03472aa17f8
title: Icon Folder
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { animated } from "@react-spring/three"

export default function Folder({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/icon_folder/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <animated.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="f0d7a2397f3a47b098f321d0fe068c9afbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Camera_Track" position={[500, 500, 500]} rotation={[-Math.PI, Math.PI / 4, 2.53]} scale={100}>
                  <group name="Object_5" />
                </group>
                <group name="CT_Target" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="CT_DOF" scale={0.1} />
                <group name="CO_Pivot" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Camera_Orbit" position={[5, -5, 5]} rotation={[-Math.PI / 2, Math.PI / 4, 2.53]}>
                    <group name="Object_10" />
                  </group>
                </group>
                <group name="Camera_Free" position={[-370.57, 239.08, 355.87]} rotation={[0, 0.78, -0.3]} scale={100}>
                  <group name="Object_12" />
                </group>
                <group name="Plane" rotation={[-1.67, 0, 0]} scale={100} />
                <group name="Plane001" position={[-2.6, 73.99, -7.26]} rotation={[-1.67, -0.04, 0]} scale={100} />
                <group name="Plane002" position={[1.71, 71.25, -2.01]} rotation={[-1.58, 0.03, 0]} scale={100} />
                <group name="Plane003" position={[-0.7, 69.04, 2.48]} rotation={[-1.53, -0.01, 0]} scale={100} />
                <group name="TriLamp-Back" position={[-63.28, 500, -449.4]} rotation={[2.4, -0.1, 3.05]} scale={100}>
                  <group name="Object_18" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_19" />
                  </group>
                </group>
                <group name="TriLamp-Fill" position={[-15.72, 500, 453.56]} rotation={[0.74, -0.03, 0.02]} scale={100}>
                  <group name="Object_21" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_22" />
                  </group>
                </group>
                <group name="TriLamp-Key" position={[-433.97, 500, 132.8]} rotation={[1.26, -0.79, 1.14]} scale={100}>
                  <group name="Object_24" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_25" />
                  </group>
                </group>
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_27">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_29" rotation={[-1.67, 0, 0]} scale={100} />
                    <group name="Object_31" position={[-2.6, 73.99, -7.26]} rotation={[-1.67, -0.04, 0]} scale={100} />
                    <group name="Object_33" position={[1.71, 71.25, -2.01]} rotation={[-1.58, 0.03, 0]} scale={100} />
                    <group name="Object_35" position={[-0.7, 69.04, 2.48]} rotation={[-1.53, -0.01, 0]} scale={100} />
                    <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.Material} skeleton={nodes.Object_30.skeleton} />
                    <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} skeleton={nodes.Object_32.skeleton} />
                    <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_0} skeleton={nodes.Object_34.skeleton} />
                    <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_0} skeleton={nodes.Object_36.skeleton} />
                  </group>
                </group>
                <group name="Area" position={[341.77, 328.79, 339.63]} rotation={[0, -Math.PI / 4, -Math.PI / 4]} scale={430}>
                  <group name="Object_49" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_50" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </animated.group>
  )
}

useGLTF.preload('/models/icon_folder/scene.gltf')
